### ISSUE TITLE
labeling tool usage

### ISSUE THREAD

**Issue by pmharikrishnan** [kevtan/lane-labeling#3]
@kevtan This is Harikrishnan from India. I am a PhD student working on lane detection in Indian roads. Ithe  wish to train few networks with my own data for that I wish to annotate lane images. I wish to use your tool. Please assist if possible

**Comment by kevtan** [comment]
Hi @pmharikrishnan, thanks for reaching out! This project is in a very much prototype state and would most likely not suffice for your annotating needs. I recommend you check out a tool called SuperAnnotate (link [here](https://superannotate.com/)). They have a free desktop version that I think will serve you well!
